### ISSUE TITLE
Ne fonctionne pas avec Raspbian Stretch

### ISSUE THREAD

**Issue by Atnode** [outout14/raspmonitor#8]
Raspmonitor ne fonctionne pas correctement avec la dernière version de Raspbian et avec un serveur lamp à jour.

**Comment by outout14** [comment]
Hum très étrange, j'essaierais de résoudre le problème ;)

**Comment by lapin-b** [comment]
Histoire de nous aider à cibler le problème, voici une petite série de questions:

Est-ce qu'il y a des erreurs ? Si oui, lesquelles ?
Quelle est ta version de PHP ?
Comment le bug se produit-il ?
Est-ce que les paquets sont à jour ?
Quel est ton serveur HTTP (Apache, NGINX, etc.) ?
Etc...

Essaye de donner un maximum d'informations qui permettront de cibler la source du *ça ne fonctionne pas*.

**Comment by outout14** [comment]
Solved - Résolu @Atnode ! :wink:
